name: novelflex
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2+3
#android next version == 1.0.6+6
#ios next version == 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  flutter_phoenix: ^1.1.0
  internet_connection_checker_plus: ^1.0.1
  provider: ^6.0.1
  localization: ^2.1.0
  flutter_localization: ^0.1.9
  country_code_picker: ^2.0.1
  fluttertoast: ^8.0.2
  connectivity: ^3.0.6
  intl: ^0.17.0
  http: ^0.13.5
  http_parser: ^4.0.1
  file_picker: ^5.2.4
  image_picker: any
  path_provider: ^2.0.4
  path: any
  dio: ^4.0.6
  getwidget: ^3.0.1
  flutter_cached_pdfview: any
  carousel_slider: any
  rating_dialog: ^2.0.4
  dio_http_cache: ^0.3.0
  cached_network_image: ^3.1.0
  translator: ^0.1.7
  url_launcher: ^6.1.6
  new_version_plus: ^0.0.1+4
  in_app_update: ^4.0.1
  app_version_update: ^2.0.3
  flutter_svg: ^1.1.6
  custom_signin_buttons: ^1.0.0
  advance_pdf_viewer2: ^2.0.4
  syncfusion_flutter_pdfviewer: ^20.4.38
  google_mobile_ads: ^1.2.0

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  flutter_localizations:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/Novelflex_main.png"
  image_path_android: "assets/Novelflex_main.png"
  remove_alpha_ios: true

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/quotes_data/
    - assets/quotes_data/extra_pngs/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
